INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Nigel','Sheldon');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Ozzie','Isaacs');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Mellanie','Rescorai');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Justine','Burnelli');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Bradley','Johansson');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (6, 'Mark','Vernon');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (7, 'Dudley','Bose');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (8, 'Paula','Myo');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (9, 'Alessandra','Barron');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (10,'Kazimir','Burnelli');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (11,'Bruce','McFoster');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (12,'Gore','Burnelli');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (13,'Kazimir','McFoster');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (14,'Oscar','Monroe');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (15,'Anna','Kime');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (16,'Tiger','Pansy');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (17,'Catherine','Stewart');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME) VALUES (18,'Stig','McSobel');

INSERT INTO LINE_ITEM (ID, DESCRIPTION, AMOUNT, USER_ID) VALUES (1, 'BOOK', 23.02, 1);
INSERT INTO LINE_ITEM (ID, DESCRIPTION, AMOUNT, USER_ID) VALUES (2, 'CHAIR', 102.02, 1);
INSERT INTO LINE_ITEM (ID, DESCRIPTION, AMOUNT, USER_ID) VALUES (3, 'COFFEE', 3.00, 1);
INSERT INTO LINE_ITEM (ID, DESCRIPTION, AMOUNT, USER_ID) VALUES (4, 'CAKE', 5.00, 1);
INSERT INTO LINE_ITEM (ID, DESCRIPTION, AMOUNT, USER_ID) VALUES (5, 'COFFEE', 5.00, 2);

commit;