CREATE TABLE USER
(
    ID         NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR(256),
    LAST_NAME  VARCHAR(256)
);

CREATE TABLE LINE_ITEM
(
    ID          NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR(256),
    AMOUNT      NUMERIC(18, 2),
    USER_ID     NUMBER REFERENCES USER(ID)
);
